version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
        POSTGRES_DB: app
        POSTGRES_PASSWORD: ChangeMe
        POSTGRES_USER: symfony
    volumes:
        - database_data:/var/lib/postgresql/data:rw
    ports:
        - 5432:5432
    networks:
        - dev

  phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin_docker_symfony
      restart: always
      depends_on:
          - database
      ports:
          - 8080:80
      environment:
          PMA_HOST: database
      networks:
          - dev


networks:
    dev:

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
